### ISSUE TITLE
Generate cert get stuck forever

### ISSUE THREAD

**Issue by Zer0-Tolerance** [jberger/Mojo-ACME#2]
Hi,
I'm trying to test the cert generation process but it seems to get stuck on both prod and test when doing
`perl script.pl acme cert generate -t -a testaccount.key mydomain.com`
here is the output
1 140734679249056 /O=Digital Signature Trust Co./CN=DST Root CA X3/O=Digital Signature Trust Co./CN=DST Root CA X3 0 140368583196528 3
Authority: /O=Digital Signature Trust Co./CN=DST Root CA X3/O=Digital Signature Trust Co./CN=DST Root CA X3
1 140734679249056 /O=Digital Signature Trust Co./CN=DST Root CA X3/C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1 0 140368594088592 2
Authority: /O=Digital Signature Trust Co./CN=DST Root CA X3/C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1
1 140734679249056 /C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52 0 140368594082992 1
Authority: /C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52
1 140734679249056 /C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52/CN=letsencrypt.org/O=INTERNET SECURITY RESEARCH GROUP/L=Mountain View/ST=California/C=US 0 140368594077248 0
Authority: /C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52/CN=letsencrypt.org/O=INTERNET SECURITY RESEARCH GROUP/L=Mountain View/ST=California/C=US
1 140734679248192 /O=Digital Signature Trust Co./CN=DST Root CA X3/O=Digital Signature Trust Co./CN=DST Root CA X3 0 140368595549824 3
Authority: /O=Digital Signature Trust Co./CN=DST Root CA X3/O=Digital Signature Trust Co./CN=DST Root CA X3
1 140734679248192 /O=Digital Signature Trust Co./CN=DST Root CA X3/C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1 0 140368596177792 2
Authority: /O=Digital Signature Trust Co./CN=DST Root CA X3/C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1
1 140734679248192 /C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52 0 140368596175632 1
Authority: /C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52
1 140734679248192 /C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52/CN=_.api.letsencrypt.org/O=INTERNET SECURITY RESEARCH GROUP/L=Mountain View/ST=California/C=US 0 140368596173376 0
Authority: /C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52/CN=_.api.letsencrypt.org/O=INTERNET SECURITY RESEARCH GROUP/L=Mountain View/ST=California/C=US

**Comment by jberger** [comment]
By output, do you mean STOUT or written to a file? STDOUT shouldn't be anything like that, nor should the written files tbh. Can you please give more detail?

**Comment by Zer0-Tolerance** [comment]
the output is coming from STDOUT, I'm running perl 5.23.1 on OSX

**Comment by jberger** [comment]
I still have never been able to replicate this exact problem, but since this time other timing bugs have been fixed and better warnings are emitted on failed requests. I'm going to close for now. please open a new bug if it should happen again.
