### ISSUE TITLE
Missing documentation in Mojolicious::Plugin::ACME

### ISSUE THREAD

**Issue by cpansprout** [jberger/Mojo-ACME#4]
The docs for Mojo::ACME 0.03 say:

```
Those options can be seen in the L<Mojolicious::Plugin::ACME> documentation.
```

But Mojolicious::Plugin::ACME just contains this:

```
=head1 NAME

Mojolicious::Plugin::ACME - ACME client integration for your Mojolicious app
```

So where is the documentation for the plugin config options?

**Comment by jberger** [comment]
This was an oversight and will be fixed soon. Thanks.
