### ISSUE TITLE
Better error checking and reporting

### ISSUE THREAD

**Issue by 0xAF** [jberger/Mojo-ACME#8]
Better error checking and reporting.
For example here: https://github.com/jberger/Mojo-ACME/blob/master/lib/Mojo/ACME.pm#L109
could be written as
```die "Could not get nonce\n".$tx->res->error->{message} unless @$nonces;```
or better with the result method as you mentioned in irc.

**Comment by s1037989** [comment]
I also had a problem with this line.  I kept getting "Could not get nonce" and that is all -- not very helpful.  Turns out the problem was that IO::Socket::SSL wasn't installed.

What do you think about making IO::Socket::SSL a requirement for Mojo::ACME?

**Comment by jberger** [comment]
I have gotten another report of this problem, in this case when the user couldn't connect to the outside world. I really need to find time to fix this. Someone poke me if I don't do it soon! (or you're always welcome to submit a PR ;P)
